<a href="https://colab.research.google.com/github/BharatXBhalla/LearningPyTorch-Youtube/blob/main/Rnn/Building_RNN_Scratch_attempt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [161]:
import torch.nn as nn
import torch
import torch.nn.functional as F

In [162]:
class RNN(nn.Module):
  def __init__(self,input_size,hidden_size,output_size):
    super().__init__()
    self.l1=nn.Linear(input_size+hidden_size,64)
    self.l2=nn.Linear(64,32)
    self.l3=nn.Linear(32,hidden_size)
    self.l4=nn.Linear(hidden_size,output_size)

  def forward(self,input,hidden_state):
    x=torch.cat((input,hidden_state),dim=0)
    x=self.l1(x)
    x=F.relu(self.l2(x))
    next_hidden_state=F.relu(self.l3(x))
    x=F.relu(self.l4(next_hidden_state))
    x=F.softmax(x)

    return next_hidden_state,x

In [163]:
model = RNN(26,100,26)

In [164]:
data = ["Bharat","Bhalla"]

In [165]:
x=0
for i in data:
  l=[]
  for j in list(i.lower()):
    tmp=[0 for i in range(0,26)]
    tmp[ord(j)-96-1]=1
    l.append(tmp)
  data[x]=l
  x=x+1

In [166]:
inputdata=torch.tensor(data,dtype=torch.float32)

In [167]:
inputdata.shape

torch.Size([2, 6, 26])

In [168]:
outputdata = data

for i in outputdata:
  i[len(i)-1]=[0 for j in range(0,26)]

In [169]:
outputdata=torch.tensor(outputdata,dtype=torch.float32)

In [170]:
outputdata

tensor([[[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          1., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0.]

In [173]:
from torch import optim

criterion=nn.KLDivLoss()
optimizer = optim.SGD(model.parameters(),lr=0.01)

In [183]:
num_epochs=10

for i in range(0,num_epochs):
  for j,l in zip(inputdata,outputdata):
    inital_hidden_state=torch.zeros(100,dtype=torch.float32)
    next_hidden_state=inital_hidden_state
    optimizer.zero_grad()
    for k,p in zip(j,l):
      next_hidden_state,output=model(k,next_hidden_state)
      loss = criterion(output,p)
    loss.backward()
    optimizer.step()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  from ipykernel import kernelapp as app
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:2748: UserWarning: reduction: 'mean' divides the total loss by both the batch size and the support size.'batchmean' divides only by the batch size, and aligns with the KL div math definition.'mean' will be changed to behave the same as 'batchmean' in the next major release.
  "reduction: 'mean' divides the total loss by both the batch size and the support size."


In [184]:
for j,l in zip(inputdata,outputdata):
  inital_hidden_state=torch.zeros(100,dtype=torch.float32)
  next_hidden_state=inital_hidden_state
  for k,p in zip(j,l):
    next_hidden_state,output=model(k,next_hidden_state)
    print(p)
    print(output)

tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.])
tensor([0.0370, 0.0398, 0.0391, 0.0370, 0.0370, 0.0370, 0.0370, 0.0409, 0.0407,
        0.0391, 0.0370, 0.0432, 0.0370, 0.0370, 0.0392, 0.0370, 0.0370, 0.0399,
        0.0411, 0.0370, 0.0410, 0.0370, 0.0370, 0.0370, 0.0403, 0.0370],
       grad_fn=<SoftmaxBackward0>)
tensor([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.])
tensor([0.0370, 0.0399, 0.0395, 0.0370, 0.0370, 0.0370, 0.0370, 0.0417, 0.0408,
        0.0389, 0.0370, 0.0430, 0.0370, 0.0370, 0.0392, 0.0370, 0.0370, 0.0401,
        0.0407, 0.0370, 0.0407, 0.0370, 0.0370, 0.0370, 0.0402, 0.0370],
       grad_fn=<SoftmaxBackward0>)
tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.])
tensor([0.0370, 0.0398, 0.0395, 0.0370, 0.0370, 0.0370, 0.0370, 0.0413, 0.0406,
        0.0387, 0.037

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  from ipykernel import kernelapp as app
