<a href="https://colab.research.google.com/github/BharatXBhalla/LearningPyTorch-Youtube/blob/main/autograd/pytorch_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch 

In [4]:
x = torch.randn(3, requires_grad=True)
x

tensor([-0.4960, -0.8354,  1.7661], requires_grad=True)

In [7]:
y = x + 2

In [8]:
y

tensor([1.5040, 1.1646, 3.7661], grad_fn=<AddBackward0>)

In [9]:
z = y*y*2
z

tensor([ 4.5238,  2.7125, 28.3669], grad_fn=<MulBackward0>)

In [10]:
z = z.mean()

In [11]:
z

tensor(11.8677, grad_fn=<MeanBackward0>)

In [12]:
x.grad

In [13]:
z.backward() #dz/dx

In [14]:
x.grad

tensor([2.0053, 1.5528, 5.0215])

We need to specify , requires_grad for gradient update if require
z.backward() is a jacobian product with a vector.

In [15]:
a = torch.randn(3,requires_grad=True)
a.requires_grad_(False)
a

tensor([-0.5975, -0.1776,  1.1021])

In [16]:
a = torch.randn(3,requires_grad=True)
b = a.detach()
b

tensor([ 0.2000, -1.0450,  0.7216])

In [19]:
with torch.no_grad():
 b = a +2
 print(b)

tensor([2.2000, 0.9550, 2.7216])


Some times we require gradients to be cleared up otherwise for next epoch gradients will be carried over (Sum up)

In [20]:
weights = torch.ones(4,requires_grad=True)

for epochs in range(3):
  model_output = (weights*3).sum()

  model_output.backward()

  print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [22]:
weights = torch.ones(4,requires_grad=True)

for epochs in range(3):
  model_output = (weights*3).sum()

  model_output.backward()

  print(weights.grad)

  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
