<a href="https://colab.research.google.com/github/BharatXBhalla/LearningPyTorch-Youtube/blob/main/tensors/01_tensor_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Tensor

In [1]:
import torch 

In [2]:
x = torch.empty(1)
x

tensor([28490.3750])

In [3]:
x = torch.empty(2,2,3)
x

tensor([[[2.8491e+04, 3.0644e-41, 5.0447e-44],
         [0.0000e+00,        nan, 0.0000e+00]],

        [[1.3788e-14, 3.6423e-06, 2.0699e-19],
         [3.3738e-12, 7.4086e+28, 6.9397e+22]]])

In [4]:
x = torch.rand(2,2)
x

tensor([[0.9799, 0.2709],
        [0.6993, 0.4797]])

In [5]:
x.dtype

torch.float32

In [6]:
x = torch.rand(2,2,dtype=torch.float16)

In [7]:
x

tensor([[0.3999, 0.0664],
        [0.9072, 0.3291]], dtype=torch.float16)

In [8]:
x.size()

torch.Size([2, 2])

### List to Tensor

In [9]:
x = torch.tensor([2.3,4.5])
x

tensor([2.3000, 4.5000])

In [10]:
x = torch.rand(2,2)
y = torch.rand(2,2)

In [11]:
x

tensor([[0.8207, 0.6683],
        [0.0936, 0.9649]])

In [12]:
y

tensor([[0.8447, 0.5866],
        [0.0866, 0.6760]])

In [13]:
z = x+y

In [14]:
z

tensor([[1.6654, 1.2549],
        [0.1801, 1.6409]])

In [15]:
y.add_(x) #inplace addition

tensor([[1.6654, 1.2549],
        [0.1801, 1.6409]])

In [16]:
y.sub_(y)

tensor([[0., 0.],
        [0., 0.]])

In [17]:
z = torch.mul(x,x)

In [18]:
z

tensor([[0.6736, 0.4466],
        [0.0088, 0.9310]])

In [19]:
z/z

tensor([[1., 1.],
        [1., 1.]])

In [20]:
z

tensor([[0.6736, 0.4466],
        [0.0088, 0.9310]])

In [21]:
x = torch.rand(5,3)
x

tensor([[0.3095, 0.4173, 0.8034],
        [0.0211, 0.4567, 0.8130],
        [0.3245, 0.0340, 0.3914],
        [0.5597, 0.6464, 0.5330],
        [0.6224, 0.7576, 0.1750]])

In [22]:
x [1,2]

tensor(0.8130)

In [23]:
x[1,:]

tensor([0.0211, 0.4567, 0.8130])

In [24]:
x[1,2].item()

0.8129932284355164

In [25]:
# Reshape 
x.view(15)

tensor([0.3095, 0.4173, 0.8034, 0.0211, 0.4567, 0.8130, 0.3245, 0.0340, 0.3914,
        0.5597, 0.6464, 0.5330, 0.6224, 0.7576, 0.1750])

In [26]:
#reshape
x

tensor([[0.3095, 0.4173, 0.8034],
        [0.0211, 0.4567, 0.8130],
        [0.3245, 0.0340, 0.3914],
        [0.5597, 0.6464, 0.5330],
        [0.6224, 0.7576, 0.1750]])

In [27]:
x.view(-1,5) #row view iteration

tensor([[0.3095, 0.4173, 0.8034, 0.0211, 0.4567],
        [0.8130, 0.3245, 0.0340, 0.3914, 0.5597],
        [0.6464, 0.5330, 0.6224, 0.7576, 0.1750]])

### Numpy to Tensor,Vice Versa

In [28]:
import numpy as np

In [29]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [30]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [31]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [32]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [33]:
a+=1

In [34]:
b #Tensor is updated when made changes to a(numpy)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [35]:
a

array([2., 2., 2., 2., 2.])

In [36]:
b+=1
b

tensor([3., 3., 3., 3., 3.], dtype=torch.float64)

In [37]:
a

array([3., 3., 3., 3., 3.])

#### In GPU torch , tensor is connected which means any update to numpy array is also reflected in tensor,vice versa

In [38]:
torch.cuda.is_available()

True

In [39]:
torch.version.cuda

'11.1'

In [42]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5,device=device)
  y = torch.ones(5)
  z = x+y
  print(z)

RuntimeError: ignored

In [45]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5,device=device)
  y = torch.ones(5)
  y = y.to(device)
  z = x+y
  print(z)
  z.numpy()

tensor([2., 2., 2., 2., 2.], device='cuda:0')


TypeError: ignored