<a href="https://colab.research.google.com/github/BharatXBhalla/LearningPyTorch-Youtube/blob/main/tensors/01_tensor_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Tensor

In [ ]:
import torch 

In [ ]:
x = torch.empty(1)
x

tensor([0.])

In [ ]:
x = torch.empty(2,2,3)
x

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.6444, 0.8040],
        [0.9706, 0.5668]])

In [ ]:
x.dtype

torch.float32

In [ ]:
x = torch.rand(2,2,dtype=torch.float16)

In [ ]:
x

tensor([[0.9556, 0.3975],
        [0.8691, 0.7163]], dtype=torch.float16)

In [ ]:
x.size()

torch.Size([2, 2])

### List to Tensor

In [ ]:
x = torch.tensor([2.3,4.5])
x

tensor([2.3000, 4.5000])

In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)

In [ ]:
x

tensor([[0.8660, 0.2511],
        [0.9952, 0.8859]])

In [ ]:
y

tensor([[0.5157, 0.4364],
        [0.1085, 0.1360]])

In [ ]:
z = x+y

In [ ]:
z

tensor([[1.3817, 0.6875],
        [1.1037, 1.0220]])

In [ ]:
y.add_(x) #inplace addition

tensor([[1.3817, 0.6875],
        [1.1037, 1.0220]])

In [ ]:
y.sub_(y)

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
z = torch.mul(x,x)

In [ ]:
z

tensor([[0.7500, 0.0630],
        [0.9904, 0.7848]])

In [ ]:
z/z

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
z

tensor([[0.7500, 0.0630],
        [0.9904, 0.7848]])

In [ ]:
x = torch.rand(5,3)
x

tensor([[0.2417, 0.0985, 0.3495],
        [0.9453, 0.2934, 0.1959],
        [0.1789, 0.1334, 0.7657],
        [0.1141, 0.8907, 0.5318],
        [0.3830, 0.2465, 0.3559]])

In [ ]:
x [1,2]

tensor(0.1959)

In [ ]:
x[1,:]

tensor([0.9453, 0.2934, 0.1959])

In [ ]:
x[1,2].item()

0.1959143877029419

In [ ]:
# Reshape 
x.view(15)

tensor([0.2417, 0.0985, 0.3495, 0.9453, 0.2934, 0.1959, 0.1789, 0.1334, 0.7657,
        0.1141, 0.8907, 0.5318, 0.3830, 0.2465, 0.3559])

In [ ]:
#reshape
x

tensor([[0.2417, 0.0985, 0.3495],
        [0.9453, 0.2934, 0.1959],
        [0.1789, 0.1334, 0.7657],
        [0.1141, 0.8907, 0.5318],
        [0.3830, 0.2465, 0.3559]])

In [ ]:
x.view(-1,5) #row view iteration

tensor([[0.2417, 0.0985, 0.3495, 0.9453, 0.2934],
        [0.1959, 0.1789, 0.1334, 0.7657, 0.1141],
        [0.8907, 0.5318, 0.3830, 0.2465, 0.3559]])

### Numpy to Tensor,Vice Versa

In [ ]:
import numpy as np

In [ ]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [ ]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [ ]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [ ]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [ ]:
a+=1

In [ ]:
b #Tensor is updated when made changes to a(numpy)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [ ]:
a

array([2., 2., 2., 2., 2.])

In [ ]:
b+=1
b

tensor([3., 3., 3., 3., 3.], dtype=torch.float64)

In [ ]:
a

array([3., 3., 3., 3., 3.])

#### In GPU torch , tensor is connected which means any update to numpy array is also reflected in tensor,vice versa

In [ ]:
torch.cuda.is_available()

C:\ProgramData\Anaconda3\lib\site-packages\torch\cuda\__init__.py:80: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:112.)
  return torch._C._cuda_getDeviceCount() > 0


False

In [ ]:
torch.version.cuda

'11.3'

In [ ]:
torch.cuda.current_device()

RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.

In [ ]:
!conda env list