<a href="https://colab.research.google.com/github/BharatXBhalla/LearningPyTorch-Youtube/blob/main/training_pipeline_basic/pytorch_gradient_descent_automation_level_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch 
import torch.nn as nn

In [ ]:
X = torch.tensor([[1],[2],[3],[4]],dtype=torch.float32)
Y = torch.tensor([[2],[4],[6],[8]],dtype=torch.float32)

In [ ]:
X_Test = torch.tensor([5],dtype=torch.float32)

In [ ]:
n_samples,n_feature = X.shape
model = nn.Linear(n_feature,1)

In [ ]:
model(X_Test)

tensor([1.3720], grad_fn=<AddBackward0>)

In [ ]:
model(X)

tensor([[0.3364],
        [0.5953],
        [0.8542],
        [1.1131]], grad_fn=<AddmmBackward0>)

In [ ]:
Y

tensor([[2.],
        [4.],
        [6.],
        [8.]])

In [ ]:
loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(),lr=0.01)

In [ ]:
model.parameters()

<generator object Module.parameters at 0x7f8d3c96af50>

In [ ]:
for epoch in range(1000):
  y_pred = model(X)

  l = loss(Y,y_pred)

  l.backward()

  optimizer.step()

  optimizer.zero_grad()

  if epoch %100 ==0:
    print("Epoch ",epoch," ","Loss = ",l)


Epoch  0   Loss =  tensor(8.2134e-05, grad_fn=<MseLossBackward0>)
Epoch  100   Loss =  tensor(4.5090e-05, grad_fn=<MseLossBackward0>)
Epoch  200   Loss =  tensor(2.4755e-05, grad_fn=<MseLossBackward0>)
Epoch  300   Loss =  tensor(1.3590e-05, grad_fn=<MseLossBackward0>)
Epoch  400   Loss =  tensor(7.4610e-06, grad_fn=<MseLossBackward0>)
Epoch  500   Loss =  tensor(4.0962e-06, grad_fn=<MseLossBackward0>)
Epoch  600   Loss =  tensor(2.2488e-06, grad_fn=<MseLossBackward0>)
Epoch  700   Loss =  tensor(1.2349e-06, grad_fn=<MseLossBackward0>)
Epoch  800   Loss =  tensor(6.7819e-07, grad_fn=<MseLossBackward0>)
Epoch  900   Loss =  tensor(3.7239e-07, grad_fn=<MseLossBackward0>)


In [ ]:
model(X)

tensor([[2.0007],
        [4.0004],
        [6.0000],
        [7.9996]], grad_fn=<AddmmBackward0>)

In [ ]:
Y

tensor([[2.],
        [4.],
        [6.],
        [8.]])