<a href="https://colab.research.google.com/github/BharatXBhalla/LearningPyTorch-Youtube/blob/main/backpropagation/pytorch_backpropagration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [12]:
x = torch.tensor(8.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0,requires_grad=True)

#forward Pass and compute loss
y_hat = w * x
loss = (y_hat - y)**2

print(loss)

#backward pass
loss.backward()

print(w.grad)

tensor(36., grad_fn=<PowBackward0>)
tensor(96.)


In [20]:
x = torch.tensor([8.0,8.0])
y = torch.tensor([2.0,2.0])

w = torch.tensor([1.0,1.0],requires_grad=True)

#forward Pass and compute loss
y_hat = w * x
loss = (y_hat - y)**2
loss

tensor([36., 36.], grad_fn=<PowBackward0>)

In [21]:
#backward pass
loss.backward(y)
w.grad

tensor([192., 192.])

In [22]:
w.grad.zero_()

tensor([0., 0.])